# Generated by Django 4.2 on 2023-04-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='confirm_password',
        ),
    ]
