# Generated by Django 4.2 on 2023-04-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_registration', '0002_remove_student_firstname_remove_student_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='std_registration/images/'),
        ),
    ]
