# Generated by Django 4.2 on 2023-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_registration', '0003_student_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('full_name', 'address'), name='unique_person', violation_error_message="Same Data User Request...Full_Name and Address can't be same"),
        ),
    ]
