# Generated by Django 4.2 on 2023-05-05 18:34

import django.core.validators
from django.db import migrations, models
import std_registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ('std_registration', '0005_remove_student_unique_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='std_registration/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png']), std_registration.validators.MaxFileSizeValidator(1024000, message='File size should not exceed 1mb.'), std_registration.validators.MinFileSizeValidator(10240, message='File size should be at least 10kb')]),
        ),
    ]
